name: Deploy Graasp Explorer to staging environment

# Controls when the action will run.
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [staging-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    # repository name
    name: Graasp Explorer
    uses: graasp/graasp-deploy/.github/workflows/cdelivery-ecs-explorer.yml@main
    # ecs-task-definition template file
    with:
      ecs-task-definition: .aws/task-definition-stage.json'
      tag: ${{ github.event.client_payload.tag }}
    # required secrets
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
      aws-region: ${{ secrets.AWS_REGION_STAGE }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_EXPLORE_STAGE }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_EXPLORE_STAGE }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_EXPLORE_STAGE }}
      container-name-explorer: ${{ secrets.CONTAINER_NAME_GRAASP_EXPLORE_STAGE }}
      next-public-api-host: ${{ secrets.NEXT_PUBLIC_API_HOST_STAGE }}
      next-public-google-analytics-id: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
      next-public-graasp-auth-host: ${{ secrets.NEXT_PUBLIC_GRAASP_AUTH_HOST_STAGE }}
      next-public-graasp-perform-host: ${{ secrets.NEXT_PUBLIC_GRAASP_PERFORM_HOST_STAGE }}
      next-public-graasper-id: ${{ secrets.NEXT_PUBLIC_GRAASPER_ID }}
      next-public-published-tag-id: ${{ secrets.NEXT_PUBLIC_PUBLISHED_TAG_ID }}
      port: ${{ secrets.PORT }}