name: Deploy to production environment

# Controls when the action will run
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [production-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    # Replace with repository name
    name: CD caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    uses: graasp/graasp-deploy/.github/workflows/cdeployment-ecs-explorer.yml@7b5dd84304458c3c5ab03cbbde059670f77b1687
    # Replace input ecs-task-definition with template file. Format: '.aws/<name>-prod.json'
    with:
      ecs-task-definition: '.aws/graasp-explorer-prod.json'
      tag: ${{ github.event.client_payload.tag }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-region: ${{ secrets.AWS_REGION_PROD }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_EXPLORE_PROD }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_EXPLORE_PROD }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_EXPLORE_PROD }}
      container-name-explorer: ${{ secrets.CONTAINER_NAME_GRAASP_EXPLORE_PROD }}
      next-public-api-host: ${{ secrets.NEXT_PUBLIC_API_HOST_PROD }}
      next-public-google-analytics-id: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
      next-public-graasp-auth-host: ${{ secrets.NEXT_PUBLIC_GRAASP_AUTH_HOST_PROD }}
      next-public-graasp-builder-host: ${{ secrets.BUILDER_CLIENT_HOST_PROD }}
      next-public-graasp-perform-host: ${{ secrets.PLAYER_CLIENT_HOST_PROD }}
      next-public-graasper-id: ${{ secrets.NEXT_PUBLIC_GRAASPER_ID }}
      next-public-published-tag-id: ${{ secrets.NEXT_PUBLIC_PUBLISHED_TAG_ID }}
      port: ${{ secrets.PORT }}
