name: Deploy to development environment

# Controls when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main
      - master

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    name: Graasp Library
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/library-deploy-dev.yml@v1
    # abort previous deployment if a newer one is in progress
    concurrency:
      group: deploy-development
      cancel-in-progress: true
    with:
      app-name: graasp-library
      app-version: ${{ github.sha }}
      next-public-graasp-account-host: ${{ vars.NEXT_PUBLIC_GRAASP_ACCOUNT_HOST_DEV }}
      ecs-task-definition: '.aws/graasp-library-dev.json'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      container-name-library: ${{ secrets.CONTAINER_NAME_GRAASP_EXPLORE_DEV }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GRAASP_EXPLORE_DEV }}
      ecs-cluster: ${{ secrets.ECS_CLUSTER_GRAASP_EXPLORE_DEV }}
      ecs-service: ${{ secrets.ECS_SERVICE_GRAASP_EXPLORE_DEV }}
      next-public-api-host: ${{ secrets.NEXT_PUBLIC_API_HOST_DEV }}
      next-public-domain: ${{ secrets.REACT_APP_DOMAIN_DEV }}
      next-public-ga-measurement-id: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID_DEV }}
      next-public-graasp-analytics-host: ${{ secrets.ANALYZER_CLIENT_HOST_DEV }}
      next-public-graasp-auth-host: ${{ secrets.NEXT_PUBLIC_GRAASP_AUTH_HOST_DEV }}
      next-public-graasp-builder-host: ${{ secrets.BUILDER_CLIENT_HOST_DEV }}
      next-public-graasp-perform-host: ${{ secrets.PLAYER_CLIENT_HOST_DEV }}
      next-public-graasper-id: ${{ secrets.NEXT_PUBLIC_GRAASPER_ID }}
      next-public-show-notifications: ${{ secrets.NEXT_PUBLIC_SHOW_NOTIFICATIONS }}
      # to be removed ! we do not use it anymore
      next-public-published-tag-id: ${{ secrets.NEXT_PUBLIC_PUBLISHED_TAG_ID }}
      next-public-sentry-dsn: ${{ secrets.SENTRY_DSN }}
      next-public-sentry-env: development
      port: ${{ secrets.PORT }}
